In [1]:
import sys  
sys.path.insert(1, '../')
from utils.dataset_utils import OriginalDataset
from utils.video_prediction import (train_ipf)

In [2]:
original_dataset = OriginalDataset('../datasets/droid_100_sample_pictures')
len_ = (original_dataset.__len__())
print(len_)

166


In [3]:
import torch
video_frames = []
for i in range(2):
    video_frames.append(torch.tensor(original_dataset[i], dtype=torch.float32))

In [4]:
i_frame_model = train_ipf(video_frames)

Training I-frame model...


RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [64, 2]

In [5]:
# torch.rand((video_frames[0].size(), 2))
print(video_frames[0].size())
flatten = video_frames[0].flatten(0,1)
print(flatten.size())
x = video_frames[0].size()[0]
y = video_frames[0].size()[1]
xxx = 4000
ii = xxx // y
jj = xxx % y
print(video_frames[0][ii][jj])
print(flatten[xxx])
print(i_frame_model)
input_t = torch.tensor([ii, jj], dtype=torch.float32)
print(input_t.size())
res = i_frame_model(input_t)
print(res)


torch.Size([180, 320, 3])
torch.Size([57600, 3])
tensor([36., 39., 44.])
tensor([36., 39., 44.])
SIREN(
  (hidden): Linear(in_features=2, out_features=32, bias=True)
  (output): Linear(in_features=32, out_features=3, bias=True)
)
torch.Size([2])
tensor([19.1509,  8.4962, -6.6915])


In [31]:
mydataset = FrameDataset(video_frames[0])
mydataset.__getitem__(4000)

(tensor([62, 32]), tensor([-1.0499,  1.3767, -1.5910]))